services:
  - type: web
    name: language-finder-api
    plan: free
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache
